version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"  # เปิดพอร์ต 3000 สำหรับ backend
    env_file:
      - ./server/.env  # ใช้ไฟล์ .env ในการกำหนด environment variables
    networks:
      - app-network
    restart: always

  src:
    build:
      context: ./src
    ports:
      - "5173:5173" # เปิดพอร์ต 5173 สำหรับ frontend
    depends_on:
      - server  # ให้ backend ทำงานก่อน
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

